openapi: 3.0.1
info:
  title: Fast Food API
  version: 1.0.0
paths:
  /ecs:
    get:
      responses:
        "200":
          description: "ECS response"
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: ANY
        uri: http://${alb_dns}:8080/
        connectionType: VPC_LINK
        connectionId: ${vpc_link_id}
  /lambda:
    get:
      responses:
        "200":
          description: "Lambda response"
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: ANY
        uri: http://${alb_dns}:8081/
        connectionType: VPC_LINK
        connectionId: ${vpc_link_id}
